Commit Run Tests For False

diff --git a/.github/workflows/generate-tag.yml b/.github/workflows/generate-tag.yml
--- a/.github/workflows/generate-tag.yml
+++ b/.github/workflows/generate-tag.yml
@@ -56,6 +56,18 @@ jobs:
         echo "::set-output name=new_version::$new_version"
         echo $new_version > version.txt
 
+    - name: Run tests
+      run: |
+        result=$(npm test)
+        echo "$result"
+        if [[ "$result" == *"FAIL"* ]]; then
+          echo "Tests failed: There are failing tests. Please check and fix them before continuing."
+          exit 1
+        else
+          echo "Tests passed successfully"
+        fi
+
+        
     - name: Commit new version
       if: success()
       env:
@@ -65,6 +77,7 @@ jobs:
         git commit -m "chore: bump version to ${{ steps.increment_version.outputs.new_version }}"
         git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kantikorn/Project_helloworld.git HEAD:main
 
+        
     - name: Create new tag
       if: success()
       env:
@@ -72,3 +85,6 @@ jobs:
       run: |
         git tag v${{ steps.increment_version.outputs.new_version }}
         git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kantikorn/Project_helloworld.git v${{ steps.increment_version.outputs.new_version }}
+
+    
+      
